export const CATEGORIES = [
  "Salary",
  "Business Income",
  "Inventory & Stock",
  "Staff Salaries",
  "Rent",
  "Food & Dining",
  "Restaurants",
  "Groceries",
  "Transport",
  "Fuel",
  "Shopping",
  "Entertainment",
  "Subscriptions",
  "Bills",
  "Utilities",
  "School Fees",
  "Medical",
  "Insurance",
  "Loans",
  "Savings",
  "Investments",
  "Transfers",
  "Airtime & Bundles",
  "Travel",
  "Miscellaneous",
] as const;

export type Category = (typeof CATEGORIES)[number];

export const CATEGORY_COLORS: Record<string, string> = {
  Salary: "#34d399",
  "Business Income": "#22d3ee",
  "Inventory & Stock": "#3b82f6",
  "Staff Salaries": "#a371f7",
  Rent: "#f59e0b",
  "Food & Dining": "#34d399",
  Restaurants: "#fb923c",
  Groceries: "#84cc16",
  Transport: "#22d3ee",
  Fuel: "#22d3ee",
  Shopping: "#ec4899",
  Entertainment: "#c4a8ff",
  Subscriptions: "#f472b6",
  Bills: "#f59e0b",
  Utilities: "#f59e0b",
  "School Fees": "#38bdf8",
  Medical: "#f87171",
  Insurance: "#94a3b8",
  Loans: "#f87171",
  Savings: "#34d399",
  Investments: "#2f81f7",
  Transfers: "#64748b",
  "Airtime & Bundles": "#a371f7",
  Travel: "#22d3ee",
  Miscellaneous: "#64748b",
};

export const MPESA_CHANNELS = [
  "Paybill",
  "Buy Goods (Till)",
  "Send Money",
  "Withdrawal",
  "Fuliza",
  "M-Shwari",
  "Loan",
  "Airtime/Bundles",
  "Bank Transfer",
  "Pochi la Biashara",
  "Other",
] as const;

export type MpesaChannel = (typeof MPESA_CHANNELS)[number];

export const CHANNEL_COLORS: Record<string, string> = {
  "Buy Goods (Till)": "#34d399",
  Paybill: "#3b82f6",
  "Send Money": "#a371f7",
  Withdrawal: "#f59e0b",
  "M-Shwari": "#22d3ee",
  Fuliza: "#f87171",
  Loan: "#f87171",
  "Airtime/Bundles": "#94a3b8",
  "Bank Transfer": "#64748b",
  "Pochi la Biashara": "#c4a8ff",
  Other: "#64748b",
};
